# Generated by Django 3.2 on 2022-11-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20221108_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
